// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package net.roxia.scheduler.message.protobuf;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string accessKey = 2;</code>
   * @return The accessKey.
   */
  java.lang.String getAccessKey();
  /**
   * <code>string accessKey = 2;</code>
   * @return The bytes for accessKey.
   */
  com.google.protobuf.ByteString
      getAccessKeyBytes();

  /**
   * <code>string group = 3;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 3;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string machineId = 4;</code>
   * @return The machineId.
   */
  java.lang.String getMachineId();
  /**
   * <code>string machineId = 4;</code>
   * @return The bytes for machineId.
   */
  com.google.protobuf.ByteString
      getMachineIdBytes();

  /**
   * <code>string requestId = 5;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 5;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.MessageType type = 7;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.MessageType type = 7;</code>
   * @return The type.
   */
  net.roxia.scheduler.message.protobuf.MessageType getType();
}
