// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package net.roxia.scheduler.message.protobuf;

/**
 * Protobuf enum {@code MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *客户端鉴权失败
   * </pre>
   *
   * <code>CLIENT_AUTH_ERROR = 0;</code>
   */
  CLIENT_AUTH_ERROR(0),
  /**
   * <pre>
   *连接
   * </pre>
   *
   * <code>CONNECT = 1;</code>
   */
  CONNECT(1),
  /**
   * <pre>
   *注销
   * </pre>
   *
   * <code>LOGOFF = 2;</code>
   */
  LOGOFF(2),
  /**
   * <pre>
   *注册任务
   * </pre>
   *
   * <code>REG_TASK = 3;</code>
   */
  REG_TASK(3),
  /**
   * <pre>
   *注销任务
   * </pre>
   *
   * <code>LOGOFF_TASK = 4;</code>
   */
  LOGOFF_TASK(4),
  /**
   * <pre>
   *执行任务
   * </pre>
   *
   * <code>EXECUTE_TASK = 5;</code>
   */
  EXECUTE_TASK(5),
  /**
   * <pre>
   *消息响应
   * </pre>
   *
   * <code>MESSAGE_RESPONSE = 6;</code>
   */
  MESSAGE_RESPONSE(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *客户端鉴权失败
   * </pre>
   *
   * <code>CLIENT_AUTH_ERROR = 0;</code>
   */
  public static final int CLIENT_AUTH_ERROR_VALUE = 0;
  /**
   * <pre>
   *连接
   * </pre>
   *
   * <code>CONNECT = 1;</code>
   */
  public static final int CONNECT_VALUE = 1;
  /**
   * <pre>
   *注销
   * </pre>
   *
   * <code>LOGOFF = 2;</code>
   */
  public static final int LOGOFF_VALUE = 2;
  /**
   * <pre>
   *注册任务
   * </pre>
   *
   * <code>REG_TASK = 3;</code>
   */
  public static final int REG_TASK_VALUE = 3;
  /**
   * <pre>
   *注销任务
   * </pre>
   *
   * <code>LOGOFF_TASK = 4;</code>
   */
  public static final int LOGOFF_TASK_VALUE = 4;
  /**
   * <pre>
   *执行任务
   * </pre>
   *
   * <code>EXECUTE_TASK = 5;</code>
   */
  public static final int EXECUTE_TASK_VALUE = 5;
  /**
   * <pre>
   *消息响应
   * </pre>
   *
   * <code>MESSAGE_RESPONSE = 6;</code>
   */
  public static final int MESSAGE_RESPONSE_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return CLIENT_AUTH_ERROR;
      case 1: return CONNECT;
      case 2: return LOGOFF;
      case 3: return REG_TASK;
      case 4: return LOGOFF_TASK;
      case 5: return EXECUTE_TASK;
      case 6: return MESSAGE_RESPONSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.roxia.scheduler.message.protobuf.MessageOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MessageType)
}

