// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package net.roxia.scheduler.message.protobuf;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\220\001\n\006Header\022\017\n\007version\030\001 " +
      "\001(\t\022\021\n\taccessKey\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\021\n" +
      "\tmachineId\030\004 \001(\t\022\021\n\trequestId\030\005 \001(\t\022\021\n\tt" +
      "imestamp\030\006 \001(\003\022\032\n\004type\030\007 \001(\0162\014.MessageTy" +
      "pe\"0\n\007Message\022\027\n\006header\030\001 \001(\0132\007.Header\022\014" +
      "\n\004body\030\002 \001(\t*{\n\013MessageType\022\022\n\016CONNECT_C" +
      "LIENT\020\000\022\021\n\rLOGOFF_CLIENT\020\001\022\014\n\010REG_TASK\020\002" +
      "\022\017\n\013LOGOFF_TASK\020\003\022\020\n\014EXECUTE_TASK\020\004\022\024\n\020M" +
      "ESSAGE_RESPONSE\020\005B(\n$net.roxia.scheduler" +
      ".message.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new java.lang.String[] { "Version", "AccessKey", "Group", "MachineId", "RequestId", "Timestamp", "Type", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Header", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
