// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body.proto

package net.roxia.scheduler.message.protobuf;

public final class ProtoBody {
  private ProtoBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Client)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientId = 1;</code>
     * @return The clientId.
     */
    String getClientId();
    /**
     * <code>string clientId = 1;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    String getGroup();
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    String getIp();
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string accessKey = 4;</code>
     * @return The accessKey.
     */
    String getAccessKey();
    /**
     * <code>string accessKey = 4;</code>
     * @return The bytes for accessKey.
     */
    com.google.protobuf.ByteString
        getAccessKeyBytes();
  }
  /**
   * Protobuf type {@code Client}
   */
  public static final class Client extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Client)
      ClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Client.newBuilder() to construct.
    private Client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Client() {
      clientId_ = "";
      group_ = "";
      ip_ = "";
      accessKey_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Client();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Client(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              accessKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBody.internal_static_Client_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBody.internal_static_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Client.class, Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile Object clientId_;
    /**
     * <code>string clientId = 1;</code>
     * @return The clientId.
     */
    @Override
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     * @return The bytes for clientId.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private volatile Object group_;
    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    @Override
    public String getGroup() {
      Object ref = group_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile Object ip_;
    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    @Override
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSKEY_FIELD_NUMBER = 4;
    private volatile Object accessKey_;
    /**
     * <code>string accessKey = 4;</code>
     * @return The accessKey.
     */
    @Override
    public String getAccessKey() {
      Object ref = accessKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accessKey_ = s;
        return s;
      }
    }
    /**
     * <code>string accessKey = 4;</code>
     * @return The bytes for accessKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getAccessKeyBytes() {
      Object ref = accessKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (!getAccessKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessKey_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (!getAccessKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Client)) {
        return super.equals(obj);
      }
      Client other = (Client) obj;

      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getAccessKey()
          .equals(other.getAccessKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + ACCESSKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAccessKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Client parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Client parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Client parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Client parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Client parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Client parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Client parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Client parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Client parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Client parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Client parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Client parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Client prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Client}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Client)
        ClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBody.internal_static_Client_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBody.internal_static_Client_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Client.class, Builder.class);
      }

      // Construct using net.roxia.scheduler.message.protobuf.ProtoBody.Client.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        group_ = "";

        ip_ = "";

        accessKey_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBody.internal_static_Client_descriptor;
      }

      @Override
      public Client getDefaultInstanceForType() {
        return Client.getDefaultInstance();
      }

      @Override
      public Client build() {
        Client result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Client buildPartial() {
        Client result = new Client(this);
        result.clientId_ = clientId_;
        result.group_ = group_;
        result.ip_ = ip_;
        result.accessKey_ = accessKey_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Client) {
          return mergeFrom((Client)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Client other) {
        if (other == Client.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getAccessKey().isEmpty()) {
          accessKey_ = other.accessKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Client parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Client) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object clientId_ = "";
      /**
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object group_ = "";
      /**
       * <code>string group = 2;</code>
       * @return The group.
       */
      public String getGroup() {
        Object ref = group_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string group = 2;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 2;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 2;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       * @return The ip.
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private Object accessKey_ = "";
      /**
       * <code>string accessKey = 4;</code>
       * @return The accessKey.
       */
      public String getAccessKey() {
        Object ref = accessKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accessKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string accessKey = 4;</code>
       * @return The bytes for accessKey.
       */
      public com.google.protobuf.ByteString
          getAccessKeyBytes() {
        Object ref = accessKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessKey = 4;</code>
       * @param value The accessKey to set.
       * @return This builder for chaining.
       */
      public Builder setAccessKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessKey() {
        
        accessKey_ = getDefaultInstance().getAccessKey();
        onChanged();
        return this;
      }
      /**
       * <code>string accessKey = 4;</code>
       * @param value The bytes for accessKey to set.
       * @return This builder for chaining.
       */
      public Builder setAccessKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessKey_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Client)
    }

    // @@protoc_insertion_point(class_scope:Client)
    private static final Client DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Client();
    }

    public static Client getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Client>
        PARSER = new com.google.protobuf.AbstractParser<Client>() {
      @Override
      public Client parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Client(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Client> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Client> getParserForType() {
      return PARSER;
    }

    @Override
    public Client getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    String getTaskId();
    /**
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>string taskName = 2;</code>
     * @return The taskName.
     */
    String getTaskName();
    /**
     * <code>string taskName = 2;</code>
     * @return The bytes for taskName.
     */
    com.google.protobuf.ByteString
        getTaskNameBytes();

    /**
     * <code>string taskDesc = 3;</code>
     * @return The taskDesc.
     */
    String getTaskDesc();
    /**
     * <code>string taskDesc = 3;</code>
     * @return The bytes for taskDesc.
     */
    com.google.protobuf.ByteString
        getTaskDescBytes();

    /**
     * <code>string cron = 4;</code>
     * @return The cron.
     */
    String getCron();
    /**
     * <code>string cron = 4;</code>
     * @return The bytes for cron.
     */
    com.google.protobuf.ByteString
        getCronBytes();

    /**
     * <code>int32 allowMaxFailures = 5;</code>
     * @return The allowMaxFailures.
     */
    int getAllowMaxFailures();
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      taskId_ = "";
      taskName_ = "";
      taskDesc_ = "";
      cron_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Task();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              taskName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              taskDesc_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              cron_ = s;
              break;
            }
            case 40: {

              allowMaxFailures_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBody.internal_static_Task_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBody.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Task.class, Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile Object taskId_;
    /**
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    @Override
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    @Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKNAME_FIELD_NUMBER = 2;
    private volatile Object taskName_;
    /**
     * <code>string taskName = 2;</code>
     * @return The taskName.
     */
    @Override
    public String getTaskName() {
      Object ref = taskName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskName_ = s;
        return s;
      }
    }
    /**
     * <code>string taskName = 2;</code>
     * @return The bytes for taskName.
     */
    @Override
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      Object ref = taskName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKDESC_FIELD_NUMBER = 3;
    private volatile Object taskDesc_;
    /**
     * <code>string taskDesc = 3;</code>
     * @return The taskDesc.
     */
    @Override
    public String getTaskDesc() {
      Object ref = taskDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string taskDesc = 3;</code>
     * @return The bytes for taskDesc.
     */
    @Override
    public com.google.protobuf.ByteString
        getTaskDescBytes() {
      Object ref = taskDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRON_FIELD_NUMBER = 4;
    private volatile Object cron_;
    /**
     * <code>string cron = 4;</code>
     * @return The cron.
     */
    @Override
    public String getCron() {
      Object ref = cron_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cron_ = s;
        return s;
      }
    }
    /**
     * <code>string cron = 4;</code>
     * @return The bytes for cron.
     */
    @Override
    public com.google.protobuf.ByteString
        getCronBytes() {
      Object ref = cron_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALLOWMAXFAILURES_FIELD_NUMBER = 5;
    private int allowMaxFailures_;
    /**
     * <code>int32 allowMaxFailures = 5;</code>
     * @return The allowMaxFailures.
     */
    @Override
    public int getAllowMaxFailures() {
      return allowMaxFailures_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (!getTaskNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskName_);
      }
      if (!getTaskDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, taskDesc_);
      }
      if (!getCronBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cron_);
      }
      if (allowMaxFailures_ != 0) {
        output.writeInt32(5, allowMaxFailures_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (!getTaskNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskName_);
      }
      if (!getTaskDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, taskDesc_);
      }
      if (!getCronBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cron_);
      }
      if (allowMaxFailures_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, allowMaxFailures_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Task)) {
        return super.equals(obj);
      }
      Task other = (Task) obj;

      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getTaskName()
          .equals(other.getTaskName())) return false;
      if (!getTaskDesc()
          .equals(other.getTaskDesc())) return false;
      if (!getCron()
          .equals(other.getCron())) return false;
      if (getAllowMaxFailures()
          != other.getAllowMaxFailures()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + TASKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTaskName().hashCode();
      hash = (37 * hash) + TASKDESC_FIELD_NUMBER;
      hash = (53 * hash) + getTaskDesc().hashCode();
      hash = (37 * hash) + CRON_FIELD_NUMBER;
      hash = (53 * hash) + getCron().hashCode();
      hash = (37 * hash) + ALLOWMAXFAILURES_FIELD_NUMBER;
      hash = (53 * hash) + getAllowMaxFailures();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Task)
        TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBody.internal_static_Task_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBody.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Task.class, Builder.class);
      }

      // Construct using net.roxia.scheduler.message.protobuf.ProtoBody.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        taskId_ = "";

        taskName_ = "";

        taskDesc_ = "";

        cron_ = "";

        allowMaxFailures_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBody.internal_static_Task_descriptor;
      }

      @Override
      public Task getDefaultInstanceForType() {
        return Task.getDefaultInstance();
      }

      @Override
      public Task build() {
        Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Task buildPartial() {
        Task result = new Task(this);
        result.taskId_ = taskId_;
        result.taskName_ = taskName_;
        result.taskDesc_ = taskDesc_;
        result.cron_ = cron_;
        result.allowMaxFailures_ = allowMaxFailures_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Task) {
          return mergeFrom((Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Task other) {
        if (other == Task.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getTaskName().isEmpty()) {
          taskName_ = other.taskName_;
          onChanged();
        }
        if (!other.getTaskDesc().isEmpty()) {
          taskDesc_ = other.taskDesc_;
          onChanged();
        }
        if (!other.getCron().isEmpty()) {
          cron_ = other.cron_;
          onChanged();
        }
        if (other.getAllowMaxFailures() != 0) {
          setAllowMaxFailures(other.getAllowMaxFailures());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object taskId_ = "";
      /**
       * <code>string taskId = 1;</code>
       * @return The taskId.
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private Object taskName_ = "";
      /**
       * <code>string taskName = 2;</code>
       * @return The taskName.
       */
      public String getTaskName() {
        Object ref = taskName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string taskName = 2;</code>
       * @return The bytes for taskName.
       */
      public com.google.protobuf.ByteString
          getTaskNameBytes() {
        Object ref = taskName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskName = 2;</code>
       * @param value The taskName to set.
       * @return This builder for chaining.
       */
      public Builder setTaskName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskName() {
        
        taskName_ = getDefaultInstance().getTaskName();
        onChanged();
        return this;
      }
      /**
       * <code>string taskName = 2;</code>
       * @param value The bytes for taskName to set.
       * @return This builder for chaining.
       */
      public Builder setTaskNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskName_ = value;
        onChanged();
        return this;
      }

      private Object taskDesc_ = "";
      /**
       * <code>string taskDesc = 3;</code>
       * @return The taskDesc.
       */
      public String getTaskDesc() {
        Object ref = taskDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string taskDesc = 3;</code>
       * @return The bytes for taskDesc.
       */
      public com.google.protobuf.ByteString
          getTaskDescBytes() {
        Object ref = taskDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskDesc = 3;</code>
       * @param value The taskDesc to set.
       * @return This builder for chaining.
       */
      public Builder setTaskDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskDesc = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskDesc() {
        
        taskDesc_ = getDefaultInstance().getTaskDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string taskDesc = 3;</code>
       * @param value The bytes for taskDesc to set.
       * @return This builder for chaining.
       */
      public Builder setTaskDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskDesc_ = value;
        onChanged();
        return this;
      }

      private Object cron_ = "";
      /**
       * <code>string cron = 4;</code>
       * @return The cron.
       */
      public String getCron() {
        Object ref = cron_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cron_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cron = 4;</code>
       * @return The bytes for cron.
       */
      public com.google.protobuf.ByteString
          getCronBytes() {
        Object ref = cron_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cron_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cron = 4;</code>
       * @param value The cron to set.
       * @return This builder for chaining.
       */
      public Builder setCron(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cron_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cron = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCron() {
        
        cron_ = getDefaultInstance().getCron();
        onChanged();
        return this;
      }
      /**
       * <code>string cron = 4;</code>
       * @param value The bytes for cron to set.
       * @return This builder for chaining.
       */
      public Builder setCronBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cron_ = value;
        onChanged();
        return this;
      }

      private int allowMaxFailures_ ;
      /**
       * <code>int32 allowMaxFailures = 5;</code>
       * @return The allowMaxFailures.
       */
      @Override
      public int getAllowMaxFailures() {
        return allowMaxFailures_;
      }
      /**
       * <code>int32 allowMaxFailures = 5;</code>
       * @param value The allowMaxFailures to set.
       * @return This builder for chaining.
       */
      public Builder setAllowMaxFailures(int value) {
        
        allowMaxFailures_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 allowMaxFailures = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAllowMaxFailures() {
        
        allowMaxFailures_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Task)
    }

    // @@protoc_insertion_point(class_scope:Task)
    private static final Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Task();
    }

    public static Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @Override
    public Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nbody.proto\"H\n\006Client\022\020\n\010clientId\030\001 \001(\t" +
      "\022\r\n\005group\030\002 \001(\t\022\n\n\002ip\030\003 \001(\t\022\021\n\taccessKey" +
      "\030\004 \001(\t\"b\n\004Task\022\016\n\006taskId\030\001 \001(\t\022\020\n\010taskNa" +
      "me\030\002 \001(\t\022\020\n\010taskDesc\030\003 \001(\t\022\014\n\004cron\030\004 \001(\t" +
      "\022\030\n\020allowMaxFailures\030\005 \001(\005B1\n$net.roxia." +
      "scheduler.message.protobufB\tProtoBodyb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new String[] { "ClientId", "Group", "Ip", "AccessKey", });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new String[] { "TaskId", "TaskName", "TaskDesc", "Cron", "AllowMaxFailures", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
